version: '2'

  # Configures database volumes
volumes:
  db-dhis2-data:

services:
  # Creation of dhis2 database
  dhis2_db:
    container_name: dhis2_postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9%4qP7b2H!%J
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - db-dhis2-data:/var/lib/postgresql/data    
  
  # Creation of PgAdmin4
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    #networks:
    #  - dhis2-network
    environment:
      PGADMIN_DEFAULT_EMAIL: kmatiya@pih.org
      PGADMIN_DEFAULT_PASSWORD: %^*3145(0)TxV@#
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80"

  dhis2_service:
    container_name: dhis_service_container
    restart: always
    build: .
    depends_on:
      - dhis2_db

  flask:
    build: ./dhis2_web_service/flask
    container_name: flask
    restart: always
    depends_on:
      - dhis2_db
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8081
  
  nginx:
    build: ./dhis2_web_service/nginx
    container_name: nginx
    restart: always
    depends_on:
      - dhis2_db
    ports:
      - "8090:8083"
